language: minimal

services:
  - docker

before_install:
  - docker image pull argovis/testdb:0.1

script:
  - docker network create travis
  - docker container run -d --network travis --name database argovis/testdb:0.1
  - docker container run -d --network travis --name redis argovis/redis:6.2.6
  - docker image build -t argovis/api:test .
  - docker image build -f Dockerfile-test -t testrunner:dev .
  - docker container run -d --network travis --name api argovis/api:test
  - docker container run --network travis testrunner:dev
