language: minimal

services:
  - docker

before_install:
  - docker image pull argovis/testdb:0.1

script:
  - docker network create travis
  - docker container run -d --network travis --name database argovis/testdb:0.32
  - docker container run -d --network travis --name redis redis:7.0.2
  - docker image build -t argovis/api:test .
  - docker image build -f Dockerfile-test -t testrunner:dev .
  - docker container run -d --network travis --name api --env ARGONODE=core argovis/api:test
  - docker container run --network travis testrunner:dev npm run test-core
  - docker container run --network travis testrunner:dev npm run test-helpers
  - docker container rm -f api
  - docker container run -d --network travis --name api --env ARGONODE=miami argovis/api:test
  - docker container run --network travis testrunner:dev npm run test-miami
  - docker container run --network travis testrunner:dev npm run test-helpers
  - docker container logs api
