FROM node:22.2.0-alpine3.20 as build
WORKDIR /app
# hack to avoid https://github.com/npm/cli/issues/4838
ENV HOME=/app/npmlogs
RUN mkdir /app/npmlogs && chown -R 1000660000 /app/npmlogs
COPY nodejs-server/package.json .
RUN npm install
RUN apk update
RUN chown -R 1000660000 /app/npmlogs/.npm

