openapi: 3.0.3
info:
  title: Argovis API
  description: REST API for Argo profiles, platforms, selections, BGC data, gridded products,
    etc.
  termsOfService: ''
  contact:
    name: Argovis Collaboration
    email: tbd@example.com
    url: https://argovis.colorado.edu/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '0.1'
externalDocs:
  description: Find us on GitHub
  url: https://github.com/argovis/argovis_api
servers:
  - url: 'https://argovis.colorado.edu'
    description: Server Hosted by University of Colorado, Boulder
  - url: 'http://localhost:3001'
    description: Local server for testing and development
tags: 
  - name: 'ar'
    description: 'atmospheric river shapes'
paths:
  /arShapes/findByDate:
    get:
      tags:
      - ar
      summary: shapes representing atmospheric rivers at a given date-time
      operationId: findARbyDate
      parameters:
        - $ref: '#/components/parameters/arDate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        '400':
          $ref: '#/components/responses/badRequest'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/serverError'
  /arShapes/findByID:
    get:
      tags:
      - ar
      summary: shapes representing atmospheric rivers with a given ID
      operationId: findARbyID
      parameters:
        - $ref: '#/components/parameters/arID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        '400':
          $ref: '#/components/responses/badRequest'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/serverError'
  /arShapes:
    get:
      tags:
      - ar
      summary: one instance of a shape representing an atmospheric river
      operationId: findOneAR
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        '400':
          $ref: '#/components/responses/badRequest'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/serverError'
components:
  schemas:
    arShapeSchema:
      type: object
      required:
      - _id
      - date
      - shapeID
      - geoLocation
      - date_formatted
      properties:
        _id:
          type: string
        date:
          type: string
          format: date-time
        shapeId:
          type: integer
        geoLocation:
          type: object
          properties:
            type:
              type: string
            coordinates:
              type: array
              items:
                type: array
                items:
                  type: number
                  minItems: 2
                  maxItems: 2
                uniqueItems: true
        date_formateed:
          type: string
          format: date
    errorResponse:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
        message:
          type: string
  parameters:
    arDate:
      in: query
      name: date
      required: true
      description: three hour increments starting at 2004-01-01T00:00:00 and ending at 2017-04-02T03:00:00
      schema:
        type: string
        format: date-time
      allowReserved: true
      example: '2010-01-01T00:00:00Z'
    arID:
      in: query
      name: _id
      required: true
      description: ID of an atmospheric river object
      schema: 
        type: string
      example: '1_262992'
  responses:
    badRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    notFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    serverError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'

security:
  - name: []